### PR TITLE
Change node-statsd library to hot-shots

### PR DESCRIPTION
**Pull request by mpilar**
As per https://github.com/auth0/auth0-instrumentation/issues/58 this changes the statsd library.

### CODE REVIEW

**Comment by dschenkelman** [comment]
This is a change that affects all projects (once they upgrade). @mpilar how should we roll this out? expect any regressions?

**Comment by mpilar** [comment]
From reading the changelog, the only change that would cause problems would be the renaming of the `global_tags` option to `globalTags`, but the StatsD object is constructed strictly in `buildStatsD` in `metrics_factory.js` and did not use `global_tags` to begin with, so I don't think there will be any regression. There are new options, better internal library error handling and new DataDog specific features but they are simply new methods to the StatsD object. 

Another change that might affect things is "Support multiline text in DataDog events" but I am unsure how that would affect anything. From reading the change in the code the only thing it does is `msgText.replace(/\n/g, '\\n');` when sending an event so that DataDog will unescape it.

**Comment by half-ogre** [comment]
How are we testing this against the consumers? Updating packages for the services in the vagrant box?

**Comment by mpilar** [comment]
I still don't have my vivaldi/vagrant setup but that would be a valid way to test it on an isolated environment. Do the vagrant/vivaldi setups point towards an actual StatsD endpoing (or DataDog itself)? If so then that should catch any issues. I don't think the event newlines should cause any issues but it's something to watch out for.

**Comment by Verlic** [comment]
@mpilar I recommend creating a docker-compose file in this project and create an integration test to ensure the new statsd implementation works as expected. We could easily run this in this repo without requiring other external services, and we could have a customized dockerfile that includes StatsD or even a mocked version of it to assert the interaction with the library.

Let's review this as part of the revision of docker and the environment

**Comment by mpilar** [comment]
Not even sure what the heck with that rebase, gonna do a new PR.

**Pull request closed without merging**
