### PR TITLE
Adds a sample test app to customize integration tests

### PR DESCRIPTION
**Pull request by Verlic**
This add a sample application inside the `test-app` folder. By editing the `.env` file, you can configure different configuration to test the library integration with a test app.

### CODE REVIEW

**Comment by dafortune** [comment]
Shouldn't the sample app have its own package.json and dependencies?

**Comment by Verlic** [comment]
I originally created that way, and in a separate repository. But then realized it's easier to have it when doing development. And it's a pretty simple script meant to be run locally so not sure if there's advantage to add a package.json and deps. Thoughts?

**Comment by dafortune** [comment]
I'm not sure I like dotenv changing process.env which is an object that does not belong to him, and worse, it is a global object. I would prefer it to read, leave it avaialble and then pass a `Object.assign({}, process.env, envsFromFile)` to auth0-instrumention... no side effects... in any case, this is a sample app, so does not worth the discussion. LGTM!

**Comment by dafortune** [comment]
> Thoughts?
Agree if it is meant to be used together with the code and not separated then does not worth separating the deps, specially for dev deps.

**Pull request merged**
