### PR TITLE
do not skip error reporter setup

### PR DESCRIPTION
**Pull request by boneskull**
Conditionally building the error reporting plugin is problematic in at least two ways:

- the consumer Hapi server must implement a conditional to check the presence of `agent.errorReporter`, as shown in `README.md`
- to use the `client` object as exposed on `server.plugins['auth0-instrumentation'].client`, the Hapi server must again conditionally check for the existence of this object whenever a method is to be called within it

With this change, we absolve our Hapi server from having to conditionally load the plugin.  The plugin will be present and loadable regardless of whether it is fully configured.

As per [the source](https://github.com/getsentry/raven-node/blob/master/lib/client.js#L54), when the `raven.Client()` constructor does not receive a DSN as its first parameter, the `Client` is "disabled".  Thus, it doesn't actually *require* a DSN, and we can instantiate it without.

### CODE REVIEW

**Comment by dirceu** [comment]
It should be possible to initialize the agent without errors even if `env.ERROR_REPORTER_URL` is not present (e.g. in staging environments or when running test cases). How would that work in these cases?

**Comment by dschenkelman** [comment]
should we be adding validation instead?

**Comment by boneskull** [comment]
> It should be possible to initialize the agent without errors even if env.ERROR_REPORTER_URL is not present (e.g. in staging environments or when running test cases). How would that work in these cases?

That's actually what this change enables.  Sorry if I wasn't clear.  It means that the Hapi plugin *is always available, regardless of your environment*.  Whether or not the plugin actually *does something* depends on the environment, however.

> should we be adding validation instead?

If we assert `env.ERROR_REPORTER_URL`, then the plugin cannot even be registered in Hapi within a test environment, assuming the test environment doesn't wish to report errors to a service.

**Comment by dirceu** [comment]
With [this change](https://github.com/auth0/auth0-instrumentation/commit/5f9ea403f82f6f3d437a393e8da99f745e9b7a4a) we can avoid all those conditionals when using the `errorReporter` object, while still making sure that we don't even try to send errors to the external service unless the environment is properly configured.

Does this fix your issue?

**Comment by boneskull** [comment]
@dirceu yes, that's even better. closing.

**Pull request closed without merging**
